export const GET_LINKS = 'LINK_CONSTANTS_GET_LINKS';
export const GET_LINKS_FROM_LOCAL_STORAGE = 'LINK_CONSTANTS_GET_LINKS_FROM_LOCAL_STORAGE';
export const CREATE_OR_UPDATE_LINK = 'LINK_CONSTANTS_CREATE_OR_UPDATE_LINK';
export const REMOVE_LINK = 'LINK_CONSTANTS_REMOVE_LINK';
